workerPoolSpecs:
  machineSpec:
    # Machines and GPUs: https://cloud.google.com/vertex-ai/docs/training/configure-compute#specifying_gpus
    machineType: n1-standard-4
    acceleratorType: NVIDIA_TESLA_V100
    acceleratorCount: 2
  replicaCount: 1
  pythonPackageSpec:
    # Executors: https://cloud.google.com/vertex-ai/docs/training/pre-built-containers
    executorImageUri: us-docker.pkg.dev/vertex-ai/training/pytorch-gpu.1-11:latest
    packageUris: gs://cgjhusker-bucket/trainer-0.1.tar.gz
    pythonModule: trainer.task
    # Train for 15 epochs.
    args: --epochs=15